# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db5571c0acfcd20582a29c76f067cbd92ec3a1e6f49668e5dbc52a53f31f39196f1ed4a94549ff151baf24bda9db39fd84bd3326a894b7be4512f278140a2437

test:
  secret_key_base: 8e491f855dde1ff84bc292358761b7367768457816bd2195db2a2b5e57863078dbb07136512c4ba1e2bcb9d3ab4dc13075e826646f7f58e2d94480cb5ef5b88f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
